# Type: Priority
- name: "priority: critical"
  color: "FF0000"
  description: "Critical priority issue that needs immediate attention"
- name: "priority: high"
  color: "FF4500"
  description: "High priority issue that should be addressed soon"
- name: "priority: medium"
  color: "FFA500"
  description: "Medium priority issue"
- name: "priority: low"
  color: "4169E1"
  description: "Low priority issue"

# Type Labels
- name: "type: bug"
  color: "FF1493"
  description: "Something isn't working"
- name: "type: feature"
  color: "1E90FF"
  description: "New feature request"
- name: "type: suggestion"
  color: "1E90FF"
  description: "Suggestion for improvement"
- name: "type: documentation"
  color: "32CD32"
  description: "Documentation related changes"
- name: "type: enhancement"
  color: "00CED1"
  description: "Improvement to existing features"
- name: "type: security"
  color: "FF0000"
  description: "Security related issues"
- name: "type: performance"
  color: "FFD700"
  description: "Performance related issues"
- name: "type: other"
  color: "808080"
  description: "Other type of issue"
- name: "type: duplicate"
  color: "808080"
  description: "This issue already exists"
- name: "type: help wanted"
  color: "1E90FF"
  description: "Help wanted"


# Status Labels
- name: "status: in progress"
  color: "FFD700"
  description: "Issue is currently being worked on"
- name: "status: blocked"
  color: "FF4500"
  description: "Issue is blocked by other work"
- name: "status: needs review"
  color: "DDA0DD"
  description: "Ready for review"

# Component Labels
- name: "component: GhGet"
  color: "000"
  description: "Issues related to the Grasshopper To GhJSON component"
- name: "component: GhPut"
  color: "000"
  description: "Issues related to the GhJSON To Grasshopper component"
- name: "component: AI GhGenerate"
  color: "000"
  description: "Issues related to the GhJSON Generator component"
- name: "component: AI Chat"
  color: "000"
  description: "Issues related to the Chat component"
- name: "component: AI TextEvaluate"
  color: "000"
  description: "Issues related to the AI TextEvaluate component"
- name: "component: AI TextGenerate"
  color: "000"
  description: "Issues related to the AI TextGenerate component"
- name: "component: AI ListEvaluate"
  color: "000"
  description: "Issues related to the AI ListEvaluate component"
- name: "component: AI ListFilter"
  color: "000"
  description: "Issues related to the AI ListFilter component"
- name: "component: AI ListGenerate"
  color: "000"
  description: "Issues related to the AI ListGenerate component"
- name: "component: Deconstruct Metrics"
  color: "000"
  description: "Issues related to the Deconstruct Metrics component"
