# Type: Priority
- name: "priority: critical"
  color: "FF0000"
  description: "Critical priority issue that needs immediate attention"
- name: "priority: high"
  color: "FF4500"
  description: "High priority issue that should be addressed soon"
- name: "priority: medium"
  color: "FFA500"
  description: "Medium priority issue"
- name: "priority: low"
  color: "4169E1"
  description: "Low priority issue"

# Close Labels
- name: "close: duplicate"
  color: "808080"
  description: "This issue already exists"
- name: "close: not related"
  color: "808080"
  description: "This issue is not related to the SmartHopper plugin"
- name: "close: lack of details"
  color: "808080"
  description: "This issue is missing details"
- name: "close: help not found"
  color: "808080"
  description: "This issue is missing help"

# Status Labels
- name: "status: in progress"
  color: "FFD700"
  description: "Issue is currently being worked on"
- name: "status: blocked"
  color: "FF4500"
  description: "Issue is blocked by other work"
- name: "status: needs more details"
  color: "DDA0DD"
  description: "Requires more details to proceed"
- name: "status: needs triage"
  color: "0E8A16"
  description: "Ready for triage"
- name: "status: help wanted"
  color: "E9C6C2"
  description: "Help wanted"

# Component Labels
- name: "component: GhGet"
  color: "000"
  description: "Issues related to the Grasshopper Get Components component"
- name: "component: GhPut"
  color: "000"
  description: "Issues related to the Grasshopper Put Components component"
- name: "component: GhRetrieveComponents"
  color: "000"
  description: "Issues related to the Grasshopper Retrieve Components component"
- name: "component: GhTidyUp"
  color: "000"
  description: "Issues related to the Grasshopper Tidy Up component"
- name: "component: AI GhGenerate"
  color: "000"
  description: "Issues related to the AI Grasshopper Generate Definitions component"
- name: "component: AI TextEvaluate"
  color: "000"
  description: "Issues related to the AI Text Evaluate component"
- name: "component: AI TextGenerate"
  color: "000"
  description: "Issues related to the AI Text Generate component"
- name: "component: AI ScriptReview"
  color: "000"
  description: "Issues related to the AI Script Review component"
- name: "component: AI ScriptGenerate"
  color: "000"
  description: "Issues related to the AI Script Generate component"
- name: "component: AI ListEvaluate"
  color: "000"
  description: "Issues related to the AI List Evaluate component"
- name: "component: AI ListFilter"
  color: "000"
  description: "Issues related to the AI List Filter component"
- name: "component: AI ListGenerate"
  color: "000"
  description: "Issues related to the AI List Generate component"
- name: "component: AI GroupTitle"
  color: "000"
  description: "Issues related to the AI GroupTitle component"
- name: "component: AI File Context"
  color: "000"
  description: "Issues related to the AI File Context component"
- name: "component: AI Chat"
  color: "000"
  description: "Issues related to the Chat component"
- name: "component: AI Chat Input"
  color: "000"
  description: "Issues related to the Chat Input component"
- name: "component: AI Chat Output"
  color: "000"
  description: "Issues related to the Chat Output component"
- name: "component: Context Parameters"
  color: "000"
  description: "Issues related to the Context Parameters component"
- name: "component: Deconstruct Metrics"
  color: "000"
  description: "Issues related to the Deconstruct Metrics component"
- name: "component: SaveGhJSON"
  color: "000"
  description: "Issues related to the Save GhJSON file component"
- name: "component: LoadGhJSON"
  color: "000"
  description: "Issues related to the Load GhJSON file component"

# Provider Labels
- name: "provider: MistralAI"
  color: "000"
  description: "Issues related to the MistralAI provider"
- name: "provider: OpenAI"
  color: "000"
  description: "Issues related to the OpenAI provider"

# Feature Labels
- name: "feature: Settings"
  color: "000"
  description: "Issues related to the Settings menu"
- name: "feature: AI Tools"
  color: "000"
  description: "Issues related to the AI tools"
- name: "feature: Provider Manager"
  color: "000"
  description: "Issues related to the Provider Manager"
- name: "feature: UI"
  color: "000"
  description: "Issues related to the UI features"
- name: "feature: Toolbar menu"
  color: "000"
  description: "Issues related to the Toolbar menu"
