name: 'Update Badges'
description: 'Update version and status badges in README.md (for-the-badge style only)'
inputs:
  branch:
    description: 'Branch name (for context)'
    required: false
    default: ''

outputs:
  version:
    description: 'Current version from Solution.props'
    value: ${{ steps.get-version.outputs.version }}
  badges-changed:
    description: 'Whether badges were changed'
    value: ${{ steps.update-badge.outputs.badges-changed || 'false' }}

runs:
  using: "composite"
  steps:
    - name: Get version from Solution.props
      id: get-version
      shell: bash
      run: |
        VERSION=$(grep -oP '(?<=<SolutionVersion>)[^<]+' Solution.props)
        echo "Current version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Update badges in README.md
      id: update-badge
      shell: bash
      run: |
        # Get the current version
        VERSION="${{ steps.get-version.outputs.version }}"
        echo "Current version from Solution.props: $VERSION"

        # Shields.io escaping: '-' -> '--', '_' -> '__', ' ' -> '_'
        SHIELDS_VERSION=${VERSION//_/__}
        SHIELDS_VERSION=${SHIELDS_VERSION//-/--}
        SHIELDS_VERSION=${SHIELDS_VERSION// /_}

        # Determine status color and text based on version suffix
        STATUS_COLOR="brightgreen"
        STATUS_TEXT="Stable"
        if [[ $VERSION == *"-dev"* ]]; then
          STATUS_COLOR="brown"
          STATUS_TEXT="Unstable%20Development"
        elif [[ $VERSION == *"-alpha"* ]]; then
          STATUS_COLOR="orange"
          STATUS_TEXT="Alpha"
        elif [[ $VERSION == *"-beta"* ]]; then
          STATUS_COLOR="yellow"
          STATUS_TEXT="Beta"
        elif [[ $VERSION == *"-rc"* ]]; then
          STATUS_COLOR="purple"
          STATUS_TEXT="Release%20Candidate"
        fi

        echo "Target version badge: ${SHIELDS_VERSION} / ${STATUS_COLOR}"
        echo "Target status badge: ${STATUS_TEXT} / ${STATUS_COLOR}"

        if [[ ! -f "README.md" ]]; then
          echo "README.md not found"
          echo "badges-changed=false" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Update VERSION badge (for-the-badge format only)
        # Pattern: https://img.shields.io/badge/version-{VERSION}-{COLOR}?style=for-the-badge
        sed -i -E "s|(https://img\.shields\.io/badge/version-)[^?]+-([a-zA-Z]+)(\?style=for-the-badge)|\1${SHIELDS_VERSION}-${STATUS_COLOR}\3|" README.md

        # Update STATUS badge (for-the-badge format only)
        # Pattern: https://img.shields.io/badge/status-{TEXT}-{COLOR}?style=for-the-badge
        sed -i -E "s|(https://img\.shields\.io/badge/status-)[^?]+-([a-zA-Z]+)(\?style=for-the-badge)|\1${STATUS_TEXT}-${STATUS_COLOR}\3|" README.md

        # Check if any changes were made
        if git diff --quiet README.md 2>/dev/null; then
          echo "Badges already up to date"
          echo "badges-changed=false" >> $GITHUB_OUTPUT
        else
          echo "Badges updated successfully"
          echo "badges-changed=true" >> $GITHUB_OUTPUT
        fi
