name: 'Update Badges'
description: 'Update the version and status badges in README.md (HTML for-the-badge)'
inputs:
  branch:
    description: 'Branch name (for context)'
    required: false
    default: ''

outputs:
  version:
    description: 'Current version from Solution.props'
    value: ${{ steps.get-version.outputs.version }}
  badges-changed:
    description: 'Whether badges were changed'
    value: ${{ steps.update-badge.outputs.badges-changed || 'false' }}

runs:
  using: "composite"
  steps:
    - name: Get version from Solution.props
      id: get-version
      shell: bash
      run: |
        VERSION=$(grep -oP '(?<=<SolutionVersion>)[^<]+' Solution.props)
        echo "Current version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Update badges in README.md (HTML)
      id: update-badge
      shell: bash
      run: |
        # Get the current version
        VERSION="${{ steps.get-version.outputs.version }}"
        echo "Current version from Solution.props: $VERSION"

        # Shields escaping for version: '-' -> '--', '_' -> '__', ' ' -> '_'
        SHIELDS_VERSION=${VERSION//_/__}
        SHIELDS_VERSION=${SHIELDS_VERSION//-/--}
        SHIELDS_VERSION=${SHIELDS_VERSION// /_}

        # Determine status color/text from suffix
        STATUS_COLOR="brightgreen"
        STATUS_TEXT="Stable"
        if [[ $VERSION == *"-dev"* ]]; then
          STATUS_COLOR="brown"
          STATUS_TEXT="Unstable%20Development"
        elif [[ $VERSION == *"-alpha"* ]]; then
          STATUS_COLOR="orange"
          STATUS_TEXT="Alpha"
        elif [[ $VERSION == *"-beta"* ]]; then
          STATUS_COLOR="yellow"
          STATUS_TEXT="Beta"
        elif [[ $VERSION == *"-rc"* ]]; then
          STATUS_COLOR="purple"
          STATUS_TEXT="Release%20Candidate"
        fi

        BADGES_CHANGED=false
        if [[ -f "README.md" ]]; then
          # Update VERSION badge: set color to STATUS_COLOR and replace the version segment
          if grep -q 'img.shields.io/badge/version-' README.md; then
            sed -i -E "s|(img.shields.io/badge/version-)[^-?]+-[a-zA-Z]+(\?style=for-the-badge)|\1${SHIELDS_VERSION}-${STATUS_COLOR}\2|" README.md && BADGES_CHANGED=true
            echo "Updated HTML version badge to ${SHIELDS_VERSION} with color ${STATUS_COLOR}"
          else
            echo "No HTML version badge found to update"
          fi

          # Update STATUS badge: replace status text and color
          if grep -q 'img.shields.io/badge/status-' README.md; then
            # Replace status text segment between 'status-' and '-<color>?style=for-the-badge'
            sed -i -E "s|(img.shields.io/badge/status-)[^-?]+(-)[a-zA-Z]+(\?style=for-the-badge)|\1${STATUS_TEXT}\2${STATUS_COLOR}\3|" README.md && BADGES_CHANGED=true
            echo "Updated HTML status badge to ${STATUS_TEXT} / ${STATUS_COLOR}"
          else
            echo "No HTML status badge found to update"
          fi

          echo "badges-changed=$BADGES_CHANGED" >> $GITHUB_OUTPUT
        else
          echo "README.md not found, skipping badge update"
          echo "badges-changed=false" >> $GITHUB_OUTPUT
        fi
