name: "Trailing Whitespace"
description: "Check or fix trailing whitespace and normalize line endings"
inputs:
  mode:
    description: "Operation mode: fix, check, or soft-check"
    required: false
    default: "check"
runs:
  using: "composite"
  steps:
    - name: Process trailing whitespace
      shell: bash
      run: |
        # Set the shell to continue on error
        set +e

        # Get the list of changed files
        FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -v -e '^\.' -e '/\.')

        # Initialize error code
        ERR=0

        # Process each file
        for file in $FILES; do
          if [[ -f "$file" ]]; then
            if [[ "${{ inputs.mode }}" == "fix" ]]; then
              sed -i 's/[ \t]*$//' "$file"
              # normalize to unix line endings
              sed -i 's/\r$//' "$file"
            else
              # Report trailing whitespace
              while IFS= read -r entry; do
                path="${entry%%:*}"
                num="${entry#*:}"
                if [[ "${{ inputs.mode }}" == "soft-check" ]]; then
                  echo "::warning file=$path,line=$num::Trailing whitespace found"
                else
                  echo "::error file=$path,line=$num::Trailing whitespace found"
                  ERR=1
                fi
              done < <(grep -nE '[[:blank:]]$' "$file" || true)
              # Report CRLF
              while IFS= read -r entry; do
                path="${entry%%:*}"
                num="${entry#*:}"
                if [[ "${{ inputs.mode }}" == "soft-check" ]]; then
                  echo "::warning file=$path,line=$num::CRLF found in $file:$num"
                else
                  echo "::error file=$path,line=$num::CRLF found in $file:$num"
                  ERR=1
                fi
              done < <(grep -n $'\\r$' "$file" || true)
            fi
          fi
        done
        exit $ERR
