name: "Trailing Whitespace"
description: "Check or fix trailing whitespace and normalize line endings"
inputs:
  mode:
    description: "Operation mode: fix, check, or soft-check"
    required: false
    default: "check"
runs:
  using: "composite"
  steps:
    - name: Process trailing whitespace
      shell: bash
      run: |
        # Set the shell to continue on error
        set +e

        # Get the list of changed files
        FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})

        # Initialize error code
        ERR=0

        # Process each file
        for file in $FILES; do
          if [[ -f "$file" ]]; then
            if [[ "${{ inputs.mode }}" == "fix" ]]; then
              sed -i 's/[ \t]*$//' "$file"
              # normalize to unix line endings
              sed -i 's/\r$//' "$file"
            else
              if grep -qE '[ \t]+$' "$file" || file "$file" | grep -q CRLF; then
                if [ "${{ inputs.mode }}" = "soft-check" ]; then
                  # emit a non-blocking warning
                  echo "::warning file=$file::Trailing whitespace or CRLF found in $file (run with mode=fix to auto-fix)"
                else
                  echo "Trailing whitespace or CRLF found in $file"
                  ERR=1
                fi
              fi
            fi
          fi
        done
        exit $ERR
