name: "Trailing Whitespace"
description: "Check or fix trailing whitespace and normalize line endings"
inputs:
  mode:
    description: "Operation mode: fix, check, or soft-check"
    required: false
    default: "check"
runs:
  using: "composite"
  steps:
    - name: Process trailing whitespace
      shell: bash
      run: |
        # Set the shell to continue on error
        set +e

        # Get the list of changed files
        FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -v -e '^\.' -e '/\.')

        # Initialize error code
        ERR=0

        # Process each file
        for file in $FILES; do
          if [[ -f "$file" ]]; then
            if [[ "${{ inputs.mode }}" == "fix" ]]; then
              sed -i 's/[ \t]*$//' "$file"
              # normalize to unix line endings
              sed -i 's/\r$//' "$file"
            else
              # Check trailing whitespace and CRLF with accurate line numbers
              found=0
              awk '/[[:blank:]]$/ {if ("${{ inputs.mode }}" == "soft-check") print "::warning file="FILENAME",line="FNR"::Trailing whitespace found in "FILENAME" on line "FNR" (run with mode=fix to auto-fix)"; else print "Trailing whitespace found in "FILENAME":"FNR; found=1}' "$file"
              awk '/\r$/ {if ("${{ inputs.mode }}" == "soft-check") print "::warning file="FILENAME",line="FNR"::CRLF found in "FILENAME" on line "FNR" (run with mode=fix to auto-fix)"; else print "CRLF found in "FILENAME":"FNR; found=1}' "$file"
              (( found )) && ERR=1
            fi
          fi
        done
        exit $ERR
