name: "Header Fixer"
description: "Check or fix C# file headers to match .editorconfig header template"
inputs:
  mode:
    description: "Operation mode: fix, check, or soft-check"
    required: false
    default: "check"
runs:
  using: "composite"
  steps:
    - name: Process C# file headers
      shell: bash
      env:
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
      run: |
        # Set the shell to exit on error
        set -o errexit -o pipefail

        # Set up error handling
        trap 'echo "HEADER-FIXER ERR: line $LINENO, cmd: $BASH_COMMAND" >&2' ERR

        # Debug information
        echo "Header Fixer Debug: mode=${{ inputs.mode }}, event=$GITHUB_EVENT_NAME"

        # Determine files to process: changed in PR or all .cs in src/
        if [ "$GITHUB_EVENT_NAME" = "pull_request" ] && [ -f "$GITHUB_EVENT_PATH" ]; then
          BASE_SHA=$(jq -r .pull_request.base.sha < "$GITHUB_EVENT_PATH")
          HEAD_SHA=$(jq -r .pull_request.head.sha < "$GITHUB_EVENT_PATH")
          FILES=$(git diff --name-only "$BASE_SHA" "$HEAD_SHA" -- '*.cs' || true)
        else
          # Fallback to all .cs files under src/
          FILES=$(find src -type f -name '*.cs')
        fi

        # Debug information
        # echo "DEBUG: Determined files: $FILES"
        # echo "Files to process: length=${#FILES[@]}"

        # If no files, skip
        if [ -z "$FILES" ]; then
          echo "No C# files to process"
          exit 0
        fi
        ERR=0
        FAILED_FILES=()
        for file in $FILES; do
          # echo "DEBUG: Processing file: $file"
          if [ -f "$file" ]; then
            # Skip auto-generated files
            if head -n 20 "$file" | grep -q '<auto-generated>'; then
              echo "Skipping auto-generated file $file"
              continue
            fi

            # Get year
            year=$(grep -m1 '^ \* Copyright' "$file" | grep -oE '[0-9]{4}' || true)
            # echo "DEBUG: Extracted year=$year for $file"
            [ -z "$year" ] && year=$(date +%Y)
            
            # Header template lines
            HEADER_LINES_ARRAY=(
              "/*"
              " * SmartHopper - AI-powered Grasshopper Plugin"
              " * Copyright (C) $year Marc Roca Musach"
              " *"
              " * This library is free software; you can redistribute it and/or"
              " * modify it under the terms of the GNU Lesser General Public"
              " * License as published by the Free Software Foundation; either"
              " * version 3 of the License, or (at your option) any later version."
              " */"
              ""
            )
            HEADER_LINE_COUNT=${#HEADER_LINES_ARRAY[@]}

            # Compare header per-line ignoring year
            # echo "Comparing header for $file"
            mismatch=0
            mismatch_line=0
            for ((i=0; i<HEADER_LINE_COUNT; i++)); do
              TEMPLATE_LINE=${HEADER_LINES_ARRAY[i]}
              FILE_LINE=$(sed -n "$((i+1))p" "$file")
              TEMPLATE_CAN=$(echo "$TEMPLATE_LINE" | sed -E 's/(Copyright \(C\) )[0-9]{4}/\1####/')
              CURRENT_CAN=$(echo "$FILE_LINE" | sed -E 's/(Copyright \(C\) )[0-9]{4}/\1####/')
              if [[ "$TEMPLATE_CAN" != "$CURRENT_CAN" ]]; then
                mismatch=1
                mismatch_line=$((i+1))
                break
              fi
            done
            
            # echo "Header mismatch flag for $file: $mismatch"
            # Process header mismatch
            if (( mismatch == 1 )); then
              if [ "${{ inputs.mode }}" = "fix" ]; then
                echo "Updating header in $file"
                echo "DEBUG: mismatch_line=$mismatch_line, HEADER_LINE_COUNT=$HEADER_LINE_COUNT"

                # Read file into array for selective updates
                readarray -t FILE_CONTENT < "$file"
                # Determine if full header insertion or line update
                if [ "$mismatch_line" -eq 1 ]; then
                  echo "DEBUG: Full header missing, inserting full header"
                  NEW_HEADER=$(printf "%s\n" "${HEADER_LINES_ARRAY[@]}")
                  printf "%s\n\n" "$NEW_HEADER" > "$file"
                  printf "%s\n" "${FILE_CONTENT[@]}" >> "$file"
                else
                  TEMPLATE_LINE="${HEADER_LINES_ARRAY[$((mismatch_line-1))]}"
                  echo "DEBUG: Replacing header line $mismatch_line with: $TEMPLATE_LINE"
                  FILE_CONTENT[$((mismatch_line-1))]="$TEMPLATE_LINE"
                  printf "%s\n" "${FILE_CONTENT[@]}" > "$file"
                fi
                
                # Check and fix unbalanced comment blocks in first 20 lines
                HEAD_LINES=$(head -n 20 "$file")
                OPEN_COUNT=$(grep -o '/\*' <<<"$HEAD_LINES" | wc -l || true)
                CLOSE_COUNT=$(grep -o '\*/' <<<"$HEAD_LINES" | wc -l || true)
                echo "DEBUG: OPEN_COUNT=$OPEN_COUNT, CLOSE_COUNT=$CLOSE_COUNT in first 20 lines"
                if [ "$OPEN_COUNT" -ne "$CLOSE_COUNT" ]; then
                  echo "DEBUG: Unbalanced comments in header area, fixing"
                  if [ "$OPEN_COUNT" -lt "$CLOSE_COUNT" ]; then
                    # Add missing /* before first comment line
                    awk 'NR <= 20 && /^[[:space:]]*\*/ && !x {print "/*"; x=1}1' "$file" > "${file}.tmp" && mv "${file}.tmp" "$file"
                  else
                    # Add missing */ after last comment line
                    awk 'NR <= 20 && /\*\// && !x {print; print "*/"; x=1; next}1' "$file" > "${file}.tmp" && mv "${file}.tmp" "$file"
                  fi
                fi

              elif [ "${{ inputs.mode }}" = "soft-check" ]; then
                # emit a non-blocking warning
                echo "::warning file=$file::Header mismatch in $file (run with mode=fix to auto-fix)"

              elif [ "${{ inputs.mode }}" = "check" ]; then
                # Emit error annotation and collect failure
                echo "::error file=$file,line=$mismatch_line::Header mismatch in $file"
                FAILED_FILES+=("$file:$mismatch_line")
                ERR=1
              fi
            fi
          fi
        done
        
        # Summarize failures in check mode
        if [ "${{ inputs.mode }}" = "check" ] && [ ${#FAILED_FILES[@]} -ne 0 ]; then
          echo " Header validation failed for the following files (file:line):"
          for entry in "${FAILED_FILES[@]}"; do
            path=${entry%%:*}
            ln=${entry##*:}
            echo "  - $path (line $ln)"
          done
          echo "Run with mode=fix to automatically update headers"
        elif [ "${{ inputs.mode }}" = "check" ]; then
          echo " All header validations passed"
        fi
        exit $ERR
