name: "Code Style"
description: "Run code-style checks/fixes: formatting, headers, etc."
inputs:
  mode:
    description: "Operation mode: fix or check"
    required: false
    default: "check"
  commit:
    description: "Commit?"
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Check for existing .NET SDK
      id: check-dotnet
      shell: bash
      run: |
        if dotnet --version >/dev/null 2>&1; then
          echo "installed=true" >> $GITHUB_OUTPUT
        else
          echo "installed=false" >> $GITHUB_OUTPUT
        fi
    - name: Setup .NET
      if: ${{ steps.check-dotnet.outputs.installed == 'false' }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'
    # - name: Run dotnet-format
    #   shell: bash
    #   run: |
    #     dotnet restore
    #     dotnet tool install -g dotnet-format || true
    #     export PATH="$HOME/.dotnet/tools:$PATH"
    #     if [ "${{ inputs.mode }}" = "check" ]; then
    #       dotnet format --verify-no-changes
    #     else
    #       dotnet format
    #     fi
    - id: header
      name: Process C# file headers
      continue-on-error: ${{ inputs.mode == 'check' }}
      uses: ./.github/actions/code-style/header-fixer
      with:
        mode: soft-check
    - id: whitespace
      name: Process trailing whitespace
      continue-on-error: ${{ inputs.mode == 'check' }}
      uses: ./.github/actions/code-style/trailing-whitespace
      with:
        mode: ${{ inputs.mode }}
    - id: using_sorter
      name: Process using directives
      continue-on-error: ${{ inputs.mode == 'check' }}
      uses: ./.github/actions/code-style/using-sorter
      with:
        mode: ${{ inputs.mode }}
    - id: namespace_fixer
      name: Check namespaces
      continue-on-error: ${{ inputs.mode == 'check' }}
      uses: ./.github/actions/code-style/namespace-fixer
      with:
        mode: soft-check
    - name: Fail on check errors
      if: ${{ inputs.mode == 'check' && (steps.header.outcome == 'failure' || steps.whitespace.outcome == 'failure' || steps.using_sorter.outcome == 'failure' || steps.namespace_fixer.outcome == 'failure') }}
      run: exit 1
    - name: Commit & push changes
      if: ${{ inputs.commit }}
      shell: bash
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add .
        git diff --quiet || (git commit -m "chore: automatically fix code style" && git push)
