name: 🐞 Bug Report
description: Create a report about something that is not working as expected
title: "[descriptive title here]"
labels: ["status: needs triage"]
type: Bug
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: Tell us what happened
    validations:
      required: true
  
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
    validations:
      required: true
  
  - type: input
    id: rhino-version
    attributes:
      label: Rhino Version
      description: What version of Rhino are you using?
      placeholder: e.g. RH8.13
    validations:
      required: true
  
  - type: input
    id: smarthopper-version
    attributes:
      label: SmartHopper Version
      description: What version of SmartHopper are you using?
      placeholder: e.g. 0.0.0-dev.250101
    validations:
      required: true
  
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See the error
    validations:
      required: true
  
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true
  
  - type: textarea
    id: additional-material
    attributes:
      label: Additional Material
      description: Add files or screenshots related to your bug report
    validations:
      required: false
