name: Task
description: Create a task for work that needs to be done
title: "Task: [brief title here]"
labels: ["type: task"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use this template to create a new task for work that needs to be done.
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What is the priority of this task?
      options:
        - High
        - Medium
        - Low
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: A clear and concise description of the task
      placeholder: Describe what needs to be done
    validations:
      required: true
  
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What criteria must be met for this task to be considered complete?
      placeholder: List the criteria that must be met
    validations:
      required: true
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional information, configuration, or data that might be helpful
    validations:
      required: false
  
  - type: textarea
    id: additional-material
    attributes:
      label: Additional Material
      description: Add files or screenshots related to this task
    validations:
      required: false
