//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHopper.Components.Properties {
    
    using System;
    using System.Drawing;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartHopper.Components.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap ghget {
            get {
                object obj = ResourceManager.GetObject("ghget", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap ghput {
            get {
                object obj = ResourceManager.GetObject("ghput", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap listalter {
            get {
                object obj = ResourceManager.GetObject("listalter", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap listevaluate {
            get {
                object obj = ResourceManager.GetObject("listevaluate", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap listfilter {
            get {
                object obj = ResourceManager.GetObject("listfilter", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap textevaluate {
            get {
                object obj = ResourceManager.GetObject("textevaluate", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap textalter {
            get {
                object obj = ResourceManager.GetObject("textalter", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap listgenerate {
            get {
                object obj = ResourceManager.GetObject("listgenerate", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap textgenerate {
            get {
                object obj = ResourceManager.GetObject("textgenerate", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap aichat {
            get {
                object obj = ResourceManager.GetObject("aichat", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type Bitmap.
        /// </summary>
        internal static Bitmap smarthopper {
            get {
                object obj = ResourceManager.GetObject("smarthopper", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
    }
}
