/*
 * SmartHopper - AI-powered Grasshopper Plugin
 * Copyright (C) 2024-2026 Marc Roca Musach
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, see <https://www.gnu.org/licenses/lgpl-3.0.html>.
 */

using System;
using System.Collections.Generic;
using System.Drawing;
using Grasshopper.Kernel;
using Grasshopper.Kernel.Data;
using Grasshopper.Kernel.Types;
using Newtonsoft.Json.Linq;

namespace SmartHopper.Components.Misc
{
    public class DeconstructMetricsComponent : GH_Component
    {
        public DeconstructMetricsComponent()
            : base(
                "Deconstruct SmartHopper Metrics",
                "DMetrics",
                "Deconstructs SmartHopper usage metrics into individual values. Accepts a tree of metrics and preserves branch topology in outputs.",
                "SmartHopper",
                "Utils")
        {
        }

        public override Guid ComponentGuid => new ("B8FE17D7-F146-4C94-9673-D2FA04BF7B9F");

        /// <summary>
        /// Gets the component's icon.
        /// </summary>
        protected override Bitmap Icon => Properties.Resources.metricsdeconstruct;

        protected override void RegisterInputParams(GH_InputParamManager pManager)
        {
            pManager.AddTextParameter("Metrics", "M", "SmartHopper usage metrics in JSON, generated by any AI-powered SmartHopper component. Accepts a tree to preserve branch topology.", GH_ParamAccess.tree);
        }

        protected override void RegisterOutputParams(GH_OutputParamManager pManager)
        {
            pManager.AddTextParameter("AI Provider", "P", "AI provider used", GH_ParamAccess.tree);
            pManager.AddTextParameter("AI Model", "M", "AI model used", GH_ParamAccess.tree);
            pManager.AddIntegerParameter("Input Tokens", "I", "Number of input tokens", GH_ParamAccess.tree);
            pManager.AddIntegerParameter("Output Tokens", "O", "Number of output tokens", GH_ParamAccess.tree);
            pManager.AddTextParameter("Finish Reason", "F", "Reason for finishing", GH_ParamAccess.tree);
            pManager.AddNumberParameter("Completion Time", "T", "Time taken for completion, in seconds", GH_ParamAccess.tree);
            pManager.AddNumberParameter("Context Usage", "CU", "Context usage percentage (0-100), representing how much of the model's context limit is being used. Empty if context limit is unknown.", GH_ParamAccess.tree);
            pManager.AddIntegerParameter("Data Count", "DC", "The number of data items that were processed by the component. This may not match the total number of items in your input lists. If the component is configured to process data in batches, this value indicates how many batches (or groups) of results the component needs to process.", GH_ParamAccess.tree);
            pManager.AddIntegerParameter("Iterations Count", "IC", "The number of times the component ran its calculation. If the component was set to recognize and group identical combinations of input items, it only processed each unique combination once and applied the results to all matching outputs. As a result, the iteration count may be less than the total data count.", GH_ParamAccess.tree);
            pManager.AddTextParameter("Role", "R", "Role label for each metrics entry (e.g. main, fallback:ImageToText, tool:img2text). Null for the primary call.", GH_ParamAccess.tree);
        }

        protected override void SolveInstance(IGH_DataAccess DA)
        {
            var metricsTree = new GH_Structure<GH_String>();
            if (!DA.GetDataTree(0, out metricsTree))
            {
                return;
            }

            var providers = new GH_Structure<GH_String>();
            var models = new GH_Structure<GH_String>();
            var inputTokens = new GH_Structure<GH_Integer>();
            var outputTokens = new GH_Structure<GH_Integer>();
            var finishReasons = new GH_Structure<GH_String>();
            var completionTimes = new GH_Structure<GH_Number>();
            var contextUsages = new GH_Structure<GH_Number>();
            var dataCounts = new GH_Structure<GH_Integer>();
            var iterationsCounts = new GH_Structure<GH_Integer>();
            var roles = new GH_Structure<GH_String>();

            foreach (var path in metricsTree.Paths)
            {
                var branch = metricsTree.get_Branch(path);
                if (branch == null) continue;

                foreach (GH_String item in branch)
                {
                    try
                    {
                        var token = JToken.Parse(item?.Value ?? "{}");
                        var entries = new List<JObject>();

                        if (token is JArray array)
                        {
                            foreach (var arrItem in array)
                            {
                                if (arrItem is JObject obj) entries.Add(obj);
                            }
                        }
                        else if (token is JObject singleObj)
                        {
                            entries.Add(singleObj);
                        }

                        foreach (var metricsObject in entries)
                        {
                            providers.Append(new GH_String(metricsObject["ai_provider"]?.Value<string>() ?? "Unknown"), path);
                            models.Append(new GH_String(metricsObject["ai_model"]?.Value<string>() ?? "Unknown"), path);
                            inputTokens.Append(new GH_Integer(metricsObject["tokens_input"]?.Value<int>() ?? 0), path);
                            outputTokens.Append(new GH_Integer(metricsObject["tokens_output"]?.Value<int>() ?? 0), path);
                            finishReasons.Append(new GH_String(metricsObject["finish_reason"]?.Value<string>() ?? "Unknown"), path);
                            completionTimes.Append(new GH_Number(metricsObject["completion_time"]?.Value<double>() ?? 0.0), path);

                            var contextUsagePercent = metricsObject["context_usage_percent"]?.Value<double?>();
                            contextUsages.Append(new GH_Number(contextUsagePercent.HasValue ? contextUsagePercent.Value * 100.0 : 0.0), path);

                            dataCounts.Append(new GH_Integer(metricsObject["data_count"]?.Value<int>() ?? 0), path);
                            iterationsCounts.Append(new GH_Integer(metricsObject["iterations_count"]?.Value<int>() ?? 0), path);
                            roles.Append(new GH_String(metricsObject["role"]?.Value<string>()), path);
                        }
                    }
                    catch (Exception ex)
                    {
                        this.AddRuntimeMessage(GH_RuntimeMessageLevel.Error, $"Failed to parse JSON metrics at {path}: {ex.Message}");
                    }
                }
            }

            DA.SetDataTree(0, providers);
            DA.SetDataTree(1, models);
            DA.SetDataTree(2, inputTokens);
            DA.SetDataTree(3, outputTokens);
            DA.SetDataTree(4, finishReasons);
            DA.SetDataTree(5, completionTimes);
            DA.SetDataTree(6, contextUsages);
            DA.SetDataTree(7, dataCounts);
            DA.SetDataTree(8, iterationsCounts);
            DA.SetDataTree(9, roles);
        }
    }
}
