/*
 * SmartHopper - AI-powered Grasshopper Plugin
 * Copyright (C) 2024-2026 Marc Roca Musach
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, see <https://www.gnu.org/licenses/lgpl-3.0.html>.
 */

using System;
using System.Collections.Generic;
using System.Drawing;
using Grasshopper.Kernel;
using Newtonsoft.Json.Linq;

namespace SmartHopper.Components.Misc
{
    public class DeconstructMetricsComponent : GH_Component
    {
        public DeconstructMetricsComponent()
            : base(
                "Deconstruct SmartHopper Metrics",
                "DMetrics",
                "Deconstructs SmartHopper usage metrics into individual values",
                "SmartHopper",
                "Utils")
        {
        }

        public override Guid ComponentGuid => new ("B8FE17D7-F146-4C94-9673-D2FA04BF7B9F");

        /// <summary>
        /// Gets the component's icon.
        /// </summary>
        protected override Bitmap Icon => Properties.Resources.metricsdeconstruct;

        protected override void RegisterInputParams(GH_InputParamManager pManager)
        {
            pManager.AddTextParameter("Metrics", "M", "SmartHopper usage metrics in JSON, generated by any AI-powered SmartHopper component", GH_ParamAccess.item);
        }

        protected override void RegisterOutputParams(GH_OutputParamManager pManager)
        {
            pManager.AddTextParameter("AI Provider", "P", "AI provider used", GH_ParamAccess.list);
            pManager.AddTextParameter("AI Model", "M", "AI model used", GH_ParamAccess.list);
            pManager.AddIntegerParameter("Input Tokens", "I", "Number of input tokens", GH_ParamAccess.list);
            pManager.AddIntegerParameter("Output Tokens", "O", "Number of output tokens", GH_ParamAccess.list);
            pManager.AddTextParameter("Finish Reason", "F", "Reason for finishing", GH_ParamAccess.list);
            pManager.AddNumberParameter("Completion Time", "T", "Time taken for completion, in seconds", GH_ParamAccess.list);
            pManager.AddNumberParameter("Context Usage", "CU", "Context usage percentage (0-100), representing how much of the model's context limit is being used. Empty if context limit is unknown.", GH_ParamAccess.list);
            pManager.AddIntegerParameter("Data Count", "DC", "The number of data items that were processed by the component. This may not match the total number of items in your input lists. If the component is configured to process data in batches, this value indicates how many batches (or groups) of results the component needs to process.", GH_ParamAccess.list);
            pManager.AddIntegerParameter("Iterations Count", "IC", "The number of times the component ran its calculation. If the component was set to recognize and group identical combinations of input items, it only processed each unique combination once and applied the results to all matching outputs. As a result, the iteration count may be less than the total data count.", GH_ParamAccess.list);
            pManager.AddTextParameter("Role", "R", "Role label for each metrics entry (e.g. main, fallback:ImageToText, tool:img2text). Null for the primary call.", GH_ParamAccess.list);
        }

        protected override void SolveInstance(IGH_DataAccess DA)
        {
            string? jsonMetrics = null;
            if (!DA.GetData(0, ref jsonMetrics))
            {
                return;
            }

            try
            {
                // Parse as JToken to handle both JObject (single) and JArray (multi)
                var token = JToken.Parse(jsonMetrics);
                var entries = new List<JObject>();

                if (token is JArray array)
                {
                    foreach (var item in array)
                    {
                        if (item is JObject obj)
                        {
                            entries.Add(obj);
                        }
                    }
                }
                else if (token is JObject singleObj)
                {
                    entries.Add(singleObj);
                }
                else
                {
                    this.AddRuntimeMessage(GH_RuntimeMessageLevel.Error, "Unexpected JSON format for metrics");
                    return;
                }

                var providers = new List<string>();
                var models = new List<string>();
                var inputTokensList = new List<int>();
                var outputTokensList = new List<int>();
                var finishReasons = new List<string>();
                var completionTimes = new List<double>();
                var contextUsages = new List<double>();
                var dataCounts = new List<int>();
                var iterationsCounts = new List<int>();
                var roles = new List<string>();

                foreach (var metricsObject in entries)
                {
                    providers.Add(metricsObject["ai_provider"]?.Value<string>() ?? "Unknown");
                    models.Add(metricsObject["ai_model"]?.Value<string>() ?? "Unknown");
                    inputTokensList.Add(metricsObject["tokens_input"]?.Value<int>() ?? 0);
                    outputTokensList.Add(metricsObject["tokens_output"]?.Value<int>() ?? 0);
                    finishReasons.Add(metricsObject["finish_reason"]?.Value<string>() ?? "Unknown");
                    completionTimes.Add(metricsObject["completion_time"]?.Value<double>() ?? 0.0);

                    var contextUsagePercent = metricsObject["context_usage_percent"]?.Value<double?>();
                    contextUsages.Add(contextUsagePercent.HasValue ? contextUsagePercent.Value * 100.0 : 0.0);

                    dataCounts.Add(metricsObject["data_count"]?.Value<int>() ?? 0);
                    iterationsCounts.Add(metricsObject["iterations_count"]?.Value<int>() ?? 0);
                    roles.Add(metricsObject["role"]?.Value<string>());
                }

                DA.SetDataList(0, providers);
                DA.SetDataList(1, models);
                DA.SetDataList(2, inputTokensList);
                DA.SetDataList(3, outputTokensList);
                DA.SetDataList(4, finishReasons);
                DA.SetDataList(5, completionTimes);
                DA.SetDataList(6, contextUsages);
                DA.SetDataList(7, dataCounts);
                DA.SetDataList(8, iterationsCounts);
                DA.SetDataList(9, roles);
            }
            catch (Exception ex)
            {
                this.AddRuntimeMessage(GH_RuntimeMessageLevel.Error, $"Failed to parse JSON metrics: {ex.Message}");
            }
        }
    }
}
