name: "Using Sorter"
description: "Check or fix C# using directives ordering and remove unused usings"
inputs:
  mode:
    description: "Operation mode: fix or check"
    required: false
    default: "check"
runs:
  using: "composite"
  steps:
    - name: Check for existing .NET SDK
      id: check-dotnet
      shell: bash
      run: |
        if dotnet --version >/dev/null 2>&1; then
          echo "installed=true" >> $GITHUB_OUTPUT
        else
          echo "installed=false" >> $GITHUB_OUTPUT
        fi
    - name: Setup .NET SDK
      if: ${{ steps.check-dotnet.outputs.installed == 'false' }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Run using sorter
      shell: bash
      run: |
        FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- '*.cs')
        ERR=0
        dotnet tool install -g dotnet-format || true
        export PATH="$HOME/.dotnet/tools:$PATH"
        for file in $FILES; do
          if [ -f "$file" ]; then
            if [ "${{ inputs.mode }}" = "check" ]; then
              dotnet format "$file" --verify-no-changes --fix-analyzers
            else
              dotnet format "$file" --fix-analyzers
            fi
          fi
        done
        # fail if any check error
        exit $ERR
