name: 'Get Version'
description: 'Extract the current version from Solution.props'
inputs:
  branch:
    description: 'Branch name (for context)'
    required: false
    default: ''

outputs:
  version:
    description: 'Current version from Solution.props'
    value: ${{ steps.get-version.outputs.version }}
  major:
    description: 'Major version component'
    value: ${{ steps.parse-version.outputs.major }}
  minor:
    description: 'Minor version component'
    value: ${{ steps.parse-version.outputs.minor }}
  patch:
    description: 'Patch version component'
    value: ${{ steps.parse-version.outputs.patch }}
  suffix:
    description: 'Version suffix (if any)'
    value: ${{ steps.parse-version.outputs.suffix }}

runs:
  using: "composite"
  steps:
    - name: Get version from Solution.props
      id: get-version
      shell: pwsh
      run: |
        $version = (Select-Xml -Path Solution.props -XPath "//SolutionVersion").Node.InnerText
        Write-Host "Current version: $version"
        "version=$version" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append -Encoding utf8

    - name: Parse version components
      id: parse-version
      shell: pwsh
      run: |
        $VERSION = '${{ steps.get-version.outputs.version }}'
        if ($VERSION -match '^(\d+)\.(\d+)\.(\d+)(-[A-Za-z0-9]+(\.[0-9]+)?)?$') {
          $major = $Matches[1]
          $minor = $Matches[2]
          $patch = $Matches[3]
          $suffix = $Matches[4]
          "major=$major" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append -Encoding utf8
          "minor=$minor" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append -Encoding utf8
          "patch=$patch" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append -Encoding utf8
          "suffix=$suffix" | Out-File -FilePath $Env:GITHUB_OUTPUT -Append -Encoding utf8
          Write-Host "Parsed version: Major=$major, Minor=$minor, Patch=$patch, Suffix=$suffix"
        } else {
          Write-Error "Error: Version format doesn't follow semantic versioning: $VERSION"
          exit 1
        }
