name: "Namespace Fixer"
description: "Check or fix C# file namespaces to match file path"
inputs:
  mode:
    description: "Operation mode: fix, check, or soft-check"
    required: false
    default: "check"
runs:
  using: "composite"
  steps:
    - name: Process C# namespaces
      if: always()
      shell: bash
      run: |
        # Set the shell to continue on error
        set +e

        # Get the list of changed files
        if [ -n "${{ github.event.pull_request }}" ]; then
          FILES=$(git diff --name-only "${{ github.event.pull_request.base.sha }}" "${{ github.event.pull_request.head.sha }}" -- '*.cs')
        else
          # Fallback to all .cs files when not a pull_request event
          FILES=$(find . -type f -name '*.cs')
        fi
        ERR=0
        for file in $FILES; do
          if [ -f "$file" ]; then
            # normalize path: strip leading './' and 'src/'
            fp=${file#./}
            fp=${fp#src/}
            fp_no_ext=${fp%.*}
            dir=${fp_no_ext%/*}
            ns=${dir//\//.}
            actual=$(grep -m1 '^namespace ' "$file" | cut -d ' ' -f2)
            if [ "$actual" != "$ns" ]; then
              if [ "${{ inputs.mode }}" = "fix" ]; then
                echo "Updating namespace in $file to $ns"
                sed -i "s/^namespace .*/namespace $ns/" "$file"
                echo "WARNING: References to this file may need manual updates."
              else
                if [ "${{ inputs.mode }}" = "soft-check" ]; then
                  # emit a non-blocking warning
                  echo "::warning file=$file::Namespace mismatch in $file (run with mode=fix to auto-fix)"
                else
                  echo "Namespace mismatch in $file: expected $ns but found $actual"
                  ERR=1
                fi
              fi
            fi
          fi
        done
        exit $ERR
