name: 🧪 .NET CI

# Description: This workflow runs .NET tests on the SmartHopper solution to ensure that changes do not break functionality.
# 
# Triggers:
# - push to main branch
# - pull_request targeting main, dev and release branches
# 
# Permissions:
# - contents: read - Required to read repository content
# - pull-requests: read - Required to read pull request information

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
      - release/**

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Determine version
        id: determine_version
        uses: ./.github/actions/versioning/get-version

      - name: Dotnet Build
        uses: ./.github/actions/dotnet-build
        with:
          solution: SmartHopper.sln
          configuration: Release
          signing_snk_base64: ${{ secrets.SIGNING_SNK_BASE64 }}
          libs_repo_pat: ${{ secrets.LIBS_REPO_PAT }}
          signing_pfx_base64: ${{ secrets.SIGNING_PFX_BASE64 }}
          signing_pfx_password: ${{ secrets.SIGNING_PFX_PASSWORD }}
          version: ${{ steps.determine_version.outputs.version }}

      - name: Run all tests
        run: dotnet test --no-build --configuration Release --results-directory TestResults
