name: 🧪 .NET CI

# Description: This workflow runs .NET tests on the SmartHopper solution to ensure that changes do not break functionality.
# 
# Triggers:
# - push to main branch
# - pull_request targeting main branch
# 
# Permissions:
# - contents: read - Required to read repository content
# - pull-requests: read - Required to read pull request information

on:
  push:
    branches:
      - main
      - dev
      - release/**
  pull_request:
    branches: 
      - '**'  # Run on all branches for PRs

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for existing .NET SDK
        id: check-dotnet
        shell: bash
        run: |
          if dotnet --version >/dev/null 2>&1; then
            echo "installed=true" >> $GITHUB_OUTPUT
          else
            echo "installed=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Setup .NET
        if: ${{ steps.check-dotnet.outputs.installed == 'false' }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Dotnet Build
        uses: ./.github/actions/dotnet-build
        with:
          solution: SmartHopper.sln
          configuration: Release

      - name: Run all tests
        run: dotnet test --no-build --configuration Release --results-directory TestResults
