name: 🧪 .NET CI
# Description: This workflow runs .NET tests on the SmartHopper solution to ensure that changes do not break functionality.
# 
# Triggers:
# - push to main branch
# - pull_request targeting main branch
# 
# Permissions:
# - contents: read - Required to read repository content
# - pull-requests: read - Required to read pull request information

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore SmartHopper.sln

      - name: Build solution
        run: dotnet build --no-restore --configuration Release SmartHopper.sln

      - name: Run all tests
        run: dotnet test --no-build --configuration Release --results-directory TestResults
