name: 🧪 .NET CI
# Description: This workflow runs .NET tests on the SmartHopper solution to ensure that changes do not break functionality.
# 
# Triggers:
# - push to main branch
# - pull_request targeting main branch
# 
# Permissions:
# - contents: read - Required to read repository content
# - pull-requests: read - Required to read pull request information

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Prepare strong-name key
        shell: pwsh
        env:
          SIGNING_SNK_BASE64: ${{ secrets.SIGNING_SNK_BASE64 }}
        run: |
          if (-not (Test-Path signing.snk)) {
            if ($env:SIGNING_SNK_BASE64) {
              Write-Host "Decoding signing.snk from Base64 secret"
              ./Sign-StrongNames.ps1 -Base64 $env:SIGNING_SNK_BASE64
            } else {
              Write-Host "Generating temporary signing.snk"
              ./Sign-StrongNames.ps1 -Generate
            }
          } else {
            Write-Host "signing.snk already exists"
          }

      - name: Restore dependencies
        run: dotnet restore SmartHopper.sln

      - name: Build solution
        run: dotnet build --no-restore --configuration Release SmartHopper.sln

      - name: Run all tests
        run: dotnet test --no-build --configuration Release --results-directory TestResults
