name: 🏷️ Close Issue on Close Label

# Description: This workflow automatically closes an issue when a "close:" type label is added.
#
# Trigger: Automatically when a label is added to an issue
#
# Permissions:
# - issues:write - Required to close issues

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  close-issue-on-label:
    runs-on: ubuntu-latest
    steps:
      - name: Close issue if close label is added
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          script: |
            const issue = context.payload.issue;
            const addedLabel = context.payload.label.name;
            
            // Check if the added label starts with "close:"
            if (addedLabel.toLowerCase().startsWith('close:')) {
              console.log(`Closing issue #${issue.number} because "${addedLabel}" label was added`);
              
              // Add a comment explaining why the issue is being closed
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: `This issue has been automatically closed because the "${addedLabel}" label was added.`
              });
              
              // Close the issue
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                state: 'closed'
              });
            }
