name: 🏁 PR Release to Main from Dev

# Description: This workflow automatically creates a PR to merge a release branch into main. When the release/* branch is merged to dev.
#
# Triggers:
# - Automatically when a PR to dev is closed
#
# Permissions:
# - contents:write - Required to create GitHub releases
# - issues:read - Required to read issue information for release notes
# - pull-requests:read - Required to read PR information for release notes

on:
  workflow_dispatch:
  pull_request:
    types: [ closed ]
    branches:
      - dev

jobs:
  create-pr-dev-to-main:
    if: ${{ github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: dev
      - name: Set up Git user
        run: |
          git config user.name "github-actions"
          git config user.email "action@github.com"
      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "${{ github.event.pull_request.head.ref }}"
          body: "${{ github.event.pull_request.body }}"
          base: main
          branch: ${{ github.event.pull_request.base.ref }}
